import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import multer from 'multer'; import AdmZip from 'adm-zip'; import mammoth from 'mammoth'; import pdf from 'pdf-parse';
const app=express(), upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024,files:100}}); const PORT=process.env.PORT||8787;
const origins=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:(o,cb)=>!o||origins.includes(o)?cb(null,true):cb(new Error('Origin not allowed'))})); app.use(express.json({limit:'10mb'})); app.use(rateLimit({windowMs:60000,limit:120}));
const guard=(req,res,next)=>{if(process.env.ADMIN_TOKEN && req.get('x-aura-token')!==process.env.ADMIN_TOKEN)return res.status(401).json({error:'Unauthorized'});next()};
const authHeader=w=>`Basic ${Buffer.from(`${w.username}:${w.appPassword}`).toString('base64')}`;
const wpFetch=async(w,path,opts={})=>{const r=await fetch(`${w.url.replace(/\/$/,'')}/wp-json/wp/v2/${path}`,{...opts,headers:{Authorization:authHeader(w),...(opts.headers||{})}}); const t=await r.text(); let j;try{j=JSON.parse(t)}catch{j={raw:t}} if(!r.ok)throw new Error(j.message||`WordPress ${r.status}`);return j};
const slug=s=>s.toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g,'').trim().replace(/[\s_]+/g,'-').replace(/-+/g,'-');
async function termId(w,type,name){let a=await wpFetch(w,`${type}?search=${encodeURIComponent(name)}&per_page=100`);let hit=a.find(x=>x.name.toLowerCase()===name.toLowerCase());if(hit)return hit.id;return (await wpFetch(w,type,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})})).id}
async function uploadMedia(w,file,alt=''){const r=await wpFetch(w,'media',{method:'POST',headers:{'Content-Type':file.mimetype||'application/octet-stream','Content-Disposition':`attachment; filename="${file.originalname.replace(/"/g,'')}"`},body:file.buffer});if(alt)await wpFetch(w,`media/${r.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alt_text:alt})});return r}
function render(post,media={}){let html=''; for(const s of post.sections||[]){if(s.type==='heading')html+=`<h${s.level||2}>${s.text||''}</h${s.level||2}>`;else if(s.type==='paragraph'||s.type==='intro')html+=`<p>${s.content||''}</p>`;else if(s.type==='html')html+=s.content||'';else if(s.type==='image'){const m=media[s.file];html+=m?`<figure class="wp-block-image"><img src="${m.source_url}" alt="${s.alt||''}"></figure>`:`<!-- AURA:MISSING:${s.file} -->`;}else if(s.type==='ad')html+=`<!-- AURA:AD:${s.slot||'article_ad'} --><div class="aura-ad-slot" data-slot="${s.slot||'article_ad'}"></div>`;else if(s.type==='checklist')html+=`<ul>${(s.items||[]).map(x=>`<li>${x}</li>`).join('')}</ul>`;} return html}
function validate(p){const e=[]; if(!p.post_id)e.push('post_id');if(!p.title)e.push('title');if(!(p.sections||[]).length)e.push('sections');if(!p.slug)p.slug=slug(p.title||'post'); const imgs=(p.sections||[]).filter(x=>x.type==='image');return {ok:!e.length,errors:e,requiredImages:imgs.map(x=>x.file),featured:p.featured_image?.file||null}}
app.get('/health',(q,r)=>r.json({ok:true,service:'Aura Publisher Pro',version:'2.0.0'}));
app.post('/api/wp/test',guard,async(req,res)=>{try{res.json(await wpFetch(req.body.wordpress,'users/me?context=edit'))}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/validate',guard,(req,res)=>res.json(validate(req.body.post||{})));
app.post('/api/import',guard,upload.array('files',100),async(req,res)=>{try{let posts=[],assets=[];for(const f of req.files||[]){const n=f.originalname.toLowerCase();if(n.endsWith('.json')){const j=JSON.parse(f.buffer.toString());posts.push(...(Array.isArray(j)?j:(j.posts||[j])))}else if(n.endsWith('.csv')){const lines=f.buffer.toString().split(/\r?\n/).filter(Boolean),h=lines.shift().split(',').map(x=>x.trim());for(const line of lines){const c=line.match(/("[^"]*(?:""[^"]*)*"|[^,]*)(?:,|$)/g)?.map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replace(/""/g,'"'))||[];const o=Object.fromEntries(h.map((k,i)=>[k,c[i]||'']));posts.push({post_id:o.post_id||crypto.randomUUID(),title:o.title,slug:o.slug||slug(o.title||''),category:o.category?[o.category]:[],tags:o.tags?o.tags.split('|').map(x=>x.trim()):[],excerpt:o.excerpt||'',status:o.status||'draft',sections:[{type:'intro',content:o.content||o.focus||''}]})}}else if(n.endsWith('.md')||n.endsWith('.txt')||n.endsWith('.html')){const text=f.buffer.toString();posts.push({post_id:f.originalname.replace(/\..+$/,''),title:text.split(/\r?\n/).find(Boolean)?.replace(/^#+\s*/,'')||f.originalname,sections:[{type:'html',content:n.endsWith('.html')?text:`<p>${text.replace(/\n\n/g,'</p><p>')}</p>`}],status:'draft'})}else if(n.endsWith('.docx')){const x=await mammoth.convertToHtml({buffer:f.buffer});posts.push({post_id:f.originalname.replace(/\.docx$/i,''),title:f.originalname.replace(/\.docx$/i,''),sections:[{type:'html',content:x.value}],status:'draft'})}else if(n.endsWith('.pdf')){const x=await pdf(f.buffer);posts.push({post_id:f.originalname.replace(/\.pdf$/i,''),title:x.text.split(/\r?\n/).find(Boolean)||f.originalname,sections:[{type:'paragraph',content:x.text}],status:'draft'})}else if(n.endsWith('.zip')){const z=new AdmZip(f.buffer);for(const e of z.getEntries()){if(e.entryName.toLowerCase().endsWith('.json')){const j=JSON.parse(e.getData().toString());posts.push(...(Array.isArray(j)?j:(j.posts||[j])))}else if(/\.(png|jpe?g|webp)$/i.test(e.entryName))assets.push(e.entryName)}}else if(/\.(png|jpe?g|webp)$/i.test(n))assets.push(f.originalname)}res.json({posts:posts.map(p=>({...p,validation:validate(p)})),assets})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/publish',guard,upload.array('assets',100),async(req,res)=>{try{const w=JSON.parse(req.body.wordpress),p=JSON.parse(req.body.post);const v=validate(p);if(!v.ok)return res.status(422).json(v);const files=Object.fromEntries((req.files||[]).map(f=>[f.originalname,f]));const media={};for(const name of [...v.requiredImages,v.featured].filter(Boolean)){if(files[name])media[name]=await uploadMedia(w,files[name],(p.sections||[]).find(x=>x.file===name)?.alt||p.featured_image?.alt||'')}
const cats=[];for(const x of p.category||p.categories||[])cats.push(await termId(w,'categories',x));const tags=[];for(const x of p.tags||[])tags.push(await termId(w,'tags',x));const body={title:p.title,slug:p.slug||slug(p.title),excerpt:p.excerpt||'',content:render(p,media),status:p.status||'draft',categories:cats,tags,featured_media:v.featured&&media[v.featured]?.id||0};if(p.date)body.date=p.date;const out=await wpFetch(w,'posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});res.json({ok:true,id:out.id,link:out.link,status:out.status})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/generate',guard,async(req,res)=>{if(!process.env.OPENAI_API_KEY)return res.status(400).json({error:'API automation is disabled. Use ChatGPT Pro Mode import, or configure OPENAI_API_KEY.'});try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6',input:`Return only valid JSON matching Aura post schema. ${JSON.stringify(req.body)}`})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'OpenAI error');res.json(j)}catch(e){res.status(400).json({error:e.message})}});
app.use((e,q,r,n)=>r.status(400).json({error:e.message})); app.listen(PORT,()=>console.log(`Aura API :${PORT}`));
