const $=s=>document.querySelector(s),state=JSON.parse(localStorage.getItem('aura-workspace')||'{"posts":[],"assets":[],"profile":""}');
const save=()=>{state.profile=$('#profile').value;localStorage.setItem('aura-workspace',JSON.stringify(state));};
$('#api').value=localStorage.getItem('aura-api')||window.AURA_CONFIG?.API_BASE||'';$('#token').value=sessionStorage.getItem('aura-token')||'';$('#wpUrl').value=localStorage.getItem('wp-url')||'';$('#wpUser').value=localStorage.getItem('wp-user')||'';$('#profile').value=state.profile||`Mindful Adaption Standard\nFeatured image → relatable introduction → useful H2 sections → image slot → ad slot → practical examples → image slot → ad slot → action checklist → closing takeaway. Target about a 7-minute read. Vary structure and wording. Every image requires alt text.`;
function api(path,opt={}){const base=$('#api').value.replace(/\/$/,'');return fetch(base+path,{...opt,headers:{'x-aura-token':$('#token').value,...(opt.headers||{})}}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j})}
function wp(){return{url:$('#wpUrl').value.trim(),username:$('#wpUser').value.trim(),appPassword:$('#wpPass').value}}
function render(){const ps=state.posts||[];$('#total').textContent=ps.length;$('#ready').textContent=ps.filter(p=>p.validation?.ok).length;$('#issues').textContent=ps.filter(p=>!p.validation?.ok).length;$('#list').classList.toggle('empty',!ps.length);$('#list').innerHTML=ps.length?ps.map((p,i)=>`<div class="post"><div><strong>${p.title||'Untitled'}</strong><span class="${p.validation?.ok?'ok':'bad'}">${p.validation?.ok?'✓ READY':'⚠ '+(p.validation?.errors||[]).join(', ')}</span><div class="muted">${p.post_id||''}</div></div><div><button onclick="previewPost(${i})">Preview</button><button onclick="publishPost(${i})">Publish</button></div></div>`).join(''):'No posts yet. Import a batch.';save()}
window.previewPost=i=>{const p=state.posts[i],body=(p.sections||[]).map(s=>s.type==='heading'?`<h${s.level||2}>${s.text||''}</h${s.level||2}>`:s.type==='image'?`<div class="panel">IMAGE: ${s.file}</div>`:s.type==='ad'?`<div class="panel">ADVERTISEMENT: ${s.slot}</div>`:s.type==='checklist'?`<ul>${(s.items||[]).map(x=>`<li>${x}</li>`).join('')}</ul>`:`<p>${s.content||''}</p>`).join('');$('#previewBody').innerHTML=`<h1>${p.title}</h1>${body}`;$('#preview').showModal()}
window.publishPost=async i=>{const p=state.posts[i];if(!confirm(`Publish ${p.title} with status ${p.status||'draft'}?`))return;const fd=new FormData();fd.append('wordpress',JSON.stringify(wp()));fd.append('post',JSON.stringify(p));try{const j=await api('/api/publish',{method:'POST',body:fd});alert(`WordPress post #${j.id} created as ${j.status}.`)}catch(e){alert(e.message)}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#testApi').onclick=async()=>{localStorage.setItem('aura-api',$('#api').value);sessionStorage.setItem('aura-token',$('#token').value);try{const j=await api('/health');$('#health').textContent='API ONLINE';alert(j.service+' '+j.version)}catch(e){alert(e.message)}};
$('#testWp').onclick=async()=>{localStorage.setItem('wp-url',$('#wpUrl').value);localStorage.setItem('wp-user',$('#wpUser').value);try{const j=await api('/api/wp/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wordpress:wp()})});$('#wpState').textContent=`Connected as ${j.name||j.slug||j.id}`;}catch(e){$('#wpState').textContent=e.message}};
$('#importBtn').onclick=async()=>{const fd=new FormData();[...$('#files').files].forEach(f=>fd.append('files',f));try{const j=await api('/api/import',{method:'POST',body:fd});state.posts.push(...j.posts);state.assets=[...new Set([...(state.assets||[]),...j.assets])];render();document.querySelector('[data-tab=queue]').click()}catch(e){alert(e.message)}};
const drop=$('#drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');$('#files').files=e.dataTransfer.files};
$('#exportBtn').onclick=()=>{save();const safe={...state,exportedAt:new Date().toISOString(),connections:{wordpressUrl:$('#wpUrl').value,wordpressUser:$('#wpUser').value}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(safe,null,2)],{type:'application/json'}));a.download='aura-workspace.json';a.click()};
$('#importWorkspace').onclick=async()=>{const f=$('#workspaceFile').files[0];if(!f)return;Object.assign(state,JSON.parse(await f.text()));render()};$('#profile').onchange=save;render();
async function wakeAura(){
  const base=($('#api').value||'').replace(/\/$/,'');
  if(!base){ $('#health').textContent='API URL NEEDED'; return; }
  $('#health').textContent='WAKING ENGINE…';
  for(let i=0;i<24;i++){
    try{ const r=await fetch(base+'/healthz',{cache:'no-store'}); if(r.ok){ $('#health').textContent='API ONLINE'; return true; } }catch(e){}
    await new Promise(resolve=>setTimeout(resolve,5000));
  }
  $('#health').textContent='API OFFLINE — RETRY'; return false;
}
wakeAura();
