const $=s=>document.querySelector(s);const state=JSON.parse(localStorage.getItem('aura-workspace')||'{"posts":[],"profile":""}');
const save=()=>{state.profile=$('#profile').value;localStorage.setItem('aura-workspace',JSON.stringify(state))};
$('#api').value=window.AURA_CONFIG?.API_BASE||'https://aura-publisher.onrender.com';$('#wpUrl').value=localStorage.getItem('wp-url')||'';$('#wpUser').value=localStorage.getItem('wp-user')||'';$('#wpPass').value='';$('#profile').value=state.profile||'Mindful Adaption Standard — unique 7–9 minute articles, deterministic images and ads, actionable ending.';
async function api(path,opt={}){const base=(window.AURA_CONFIG?.API_BASE||$('#api').value).replace(/\/$/,'');try{const r=await fetch(base+path,{...opt,mode:'cors'}),t=await r.text();let j;try{j=t?JSON.parse(t):{}}catch{j={error:t||'Invalid server response'}}if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}catch(e){if(e instanceof TypeError)throw Error('Could not reach Aura Engine. Check Render deployment and ALLOWED_ORIGINS.');throw e}}
function wp(){return{url:$('#wpUrl').value.trim(),username:$('#wpUser').value.trim(),appPassword:$('#wpPass').value}}
const DB_NAME='aura-assets-v9',DB_STORE='assets';
const canon=n=>String(n||'').replace(/\\/g,'/').split('/').pop().trim().toLowerCase();
const dbp=new Promise((resolve,reject)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE,{keyPath:'key'})};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
async function assetPut(a){if(!a?.name||!a?.dataBase64)throw Error('Incomplete image payload returned by Aura Engine.');const rec={...a,key:canon(a.name),name:String(a.name).replace(/\\/g,'/').split('/').pop()};const db=await dbp;return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(rec);tx.oncomplete=()=>res(rec);tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||Error('Image storage transaction aborted.'))})}
async function assetGet(n){const db=await dbp;return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readonly'),q=tx.objectStore(DB_STORE).get(canon(n));q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
async function assetDelete(n){const db=await dbp;return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(canon(n));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function assetClear(){const db=await dbp;return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function assetCount(){const db=await dbp;return new Promise((res,rej)=>{const q=db.transaction(DB_STORE,'readonly').objectStore(DB_STORE).count();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');function render(){const ps=state.posts||[];$('#total').textContent=ps.length;$('#ready').textContent=ps.filter(p=>p.validation?.ok).length;$('#issues').textContent=ps.filter(p=>!p.validation?.ok).length;$('#list').classList.toggle('empty',!ps.length);$('#list').innerHTML=ps.length?ps.map((p,i)=>`<div class="post"><div><strong>${esc(p.title||'INVALID — missing title')}</strong><span class="${p.validation?.ok?'ok':'bad'}">${p.validation?.ok?'✓ READY':'✕ IMPORT INVALID: '+esc((p.validation?.errors||[]).join(' • '))}</span><div class="muted">${esc(p.post_id||'NO POST ID')}</div></div><div><button ${!p.title?'disabled':''} onclick="previewPost(${i})">Preview</button><button ${!p.validation?.ok?'disabled':''} onclick="publishPost(${i})">Publish</button><button class="danger icon-delete" title="Remove post" aria-label="Remove ${esc(p.title||'post')}" onclick="deletePost(${i})">×</button></div></div>`).join(''):'No posts yet. Import an Aura ZIP/JSON/CSV package.';save()}

window.deletePost=async i=>{const p=state.posts[i];if(!p)return;if(!confirm(`Remove ${p.title||p.post_id||'this post'} from Aura?`))return;const names=[p.featured_image?.filename,...(p.sections||[]).filter(x=>x.type==='image').map(x=>x.filename)].filter(Boolean);state.posts.splice(i,1);for(const n of names){const stillUsed=(state.posts||[]).some(x=>x.featured_image?.filename===n||(x.sections||[]).some(y=>y.type==='image'&&y.filename===n));if(!stillUsed)try{await assetDelete(n)}catch{}}render()};
window.deleteAllPosts=async()=>{if(!(state.posts||[]).length)return;if(!confirm('Remove ALL posts and locally stored image assets from Aura?'))return;state.posts=[];await assetClear();render();$('#importState').textContent='Queue cleared. Ready for a new ZIP package.'};
window.previewPost=i=>{const p=state.posts[i];if(!p)return;const body=(p.sections||[]).map(s=>s.type==='heading'?`<h${s.level||2}>${esc(s.content)}</h${s.level||2}>`:s.type==='image'?`<div class="panel"><b>IMAGE</b> ${esc(s.filename)}<br><small>${esc(s.alt_text||'')}</small></div>`:s.type==='ad'?`<div class="panel">ADVERTISEMENT: ${esc(s.slot)}</div>`:s.type==='checklist'?`<ul>${(s.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:s.type==='html'?s.content:`<p>${esc(s.content||'')}</p>`).join('');$('#previewBody').innerHTML=`<h1>${esc(p.title||'Invalid post')}</h1>${body}`;$('#preview').showModal()};
function b64blob(a){const bin=atob(a.dataBase64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:a.mime||'application/octet-stream'})}
window.publishPost=async i=>{const p=state.posts[i];if(!p?.validation?.ok)return alert('This post is not publish-ready. Fix its import errors first.');const names=[...(p.featured_image?.filename?[p.featured_image.filename]:[]),...(p.sections||[]).filter(s=>s.type==='image').map(s=>s.filename).filter(Boolean)];const loaded=[];for(const n of [...new Set(names)]){const a=await assetGet(n);if(!a){p.validation={...(p.validation||{}),ok:false,errors:[...new Set([...(p.validation?.errors||[]),`Local image not stored: ${n}`])]};render();return alert(`Image ${n} is not stored on this device. This queue entry has been marked invalid. Clear the queue and import the complete ZIP again.`)}loaded.push([n,a])}if(!confirm(`Send ${p.title} to WordPress as ${p.status||'draft'}?`))return;const fd=new FormData();fd.append('wordpress',JSON.stringify(wp()));fd.append('post',JSON.stringify(p));for(const [n,a] of loaded)fd.append('assets',b64blob(a),n);try{const j=await api('/api/publish',{method:'POST',body:fd});alert(`WordPress post #${j.id} created as ${j.status}. Uploaded ${j.uploadedImages||0} image(s).`)}catch(e){alert(e.message)}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#testApi').onclick=async()=>{try{const j=await api('/health');$('#health').textContent='API ONLINE';alert(j.service+' '+j.version)}catch(e){alert(e.message)}};
let wpTestSeq=0;function resetWpState(m='Not tested'){wpTestSeq++;$('#wpState').textContent=m;$('#wpState').className='muted'}['wpUrl','wpUser','wpPass'].forEach(id=>$('#'+id).addEventListener('input',()=>resetWpState('Credentials changed — test WordPress again.')));$('#testWp').onclick=async()=>{const seq=++wpTestSeq,btn=$('#testWp');btn.disabled=true;$('#wpState').textContent='Testing current credentials…';localStorage.setItem('wp-url',$('#wpUrl').value.trim());localStorage.setItem('wp-user',$('#wpUser').value.trim());try{const j=await api('/api/wp/test',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({wordpress:wp()})});if(seq!==wpTestSeq)return;$('#wpState').textContent=`✓ Connected as ${j.user?.name||j.user?.slug||j.user?.id} • REST: ${j.restRoot}`;$('#wpState').className='ok'}catch(e){if(seq!==wpTestSeq)return;$('#wpState').textContent=`✕ ${e.message}`;$('#wpState').className='bad'}finally{if(seq===wpTestSeq)btn.disabled=false}};$('#clearWp').onclick=()=>{localStorage.removeItem('wp-url');localStorage.removeItem('wp-user');$('#wpUrl').value=$('#wpUser').value=$('#wpPass').value='';resetWpState('Saved WordPress connection cleared.')};
async function importFiles(files){if(!files.length)return alert('Choose a ZIP, JSON, CSV, or content package first.');const fd=new FormData();[...files].forEach(f=>fd.append('files',f));$('#importState').textContent='Analyzing and storing package…';try{const j=await api('/api/import',{method:'POST',body:fd});const posts=Array.isArray(j?.posts)?j.posts:null;if(!posts)throw Error(`Unexpected Aura import response (protocol ${j?.protocolVersion||'unknown'}). Deploy the V10 backend and reload this page.`);const assets=Array.isArray(j?.assets)?j.assets:[];const required=[...new Set(posts.flatMap(p=>[p.featured_image?.filename,...(p.sections||[]).filter(x=>x.type==='image').map(x=>x.filename)].filter(Boolean)))];const byKey=new Map(assets.filter(a=>a?.name&&a?.dataBase64).map(a=>[canon(a.name),a]));const missingFromServer=required.filter(n=>!byKey.has(canon(n)));if(missingFromServer.length)throw Error(`ZIP is missing required image file(s): ${missingFromServer.slice(0,8).join(', ')}. The article manifest references these files, but they are not physically inside the ZIP.`);
// Stage images first. Queue is replaced only after every required image survives a read-back check.
await assetClear();for(const a of assets)await assetPut(a);const failed=[];for(const n of required)if(!await assetGet(n))failed.push(n);if(failed.length){await assetClear();throw Error(`Your browser could not store ${failed.length} image(s): ${failed.slice(0,8).join(', ')}. No posts were added. Make sure Safari is not in Private Browsing and try again.`)}
state.posts=posts;state.schemaVersion=10;save();render();const ready=posts.filter(p=>p.validation?.ok).length,invalid=posts.length-ready;$('#importState').textContent=`Imported ${posts.length} posts + ${assets.length} images • ${ready} ready • ${invalid} invalid • local assets verified`;document.querySelector('[data-tab=queue]').click()}catch(e){$('#importState').textContent=`Import failed — ${e.message}`;alert(e.message)}}
$('#deleteAll').onclick=deleteAllPosts;$('#importBtn').onclick=()=>importFiles($('#files').files);const drop=$('#drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');importFiles(e.dataTransfer.files)};
$('#exportBtn').onclick=()=>{save();const safe={...state,exportedAt:new Date().toISOString(),connections:{wordpressUrl:$('#wpUrl').value,wordpressUser:$('#wpUser').value},note:'Binary images remain in IndexedDB and are intentionally excluded.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(safe,null,2)],{type:'application/json'}));a.download='aura-workspace.json';a.click()};$('#importWorkspace').onclick=async()=>{const f=$('#workspaceFile').files[0];if(!f)return;Object.assign(state,JSON.parse(await f.text()));render()};$('#profile').onchange=save;if(state.schemaVersion!==10&&state.posts?.length){state.posts=[];save();assetClear().catch(()=>{});$('#importState').textContent='Older queue cleared during V10 upgrade. Import your ZIP again.'}render();
async function wakeAura(){const base=(window.AURA_CONFIG?.API_BASE||'').replace(/\/$/,'');$('#health').textContent='WAKING ENGINE…';for(let i=0;i<24;i++){try{const r=await fetch(base+'/healthz',{cache:'no-store'});if(r.ok){$('#health').textContent='API ONLINE';return}}catch{}await new Promise(r=>setTimeout(r,5000))}$('#health').textContent='API OFFLINE — RETRY'}wakeAura();
