import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import multer from 'multer'; import AdmZip from 'adm-zip'; import mammoth from 'mammoth'; import pdf from 'pdf-parse';
const app=express(), upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024,files:100}}); const PORT=process.env.PORT||8787;
const defaultOrigins=['https://zayaiken21.github.io'];
const cleanOrigin=x=>String(x||'').trim().replace(/\/+$/,'');
const origins=[...new Set([...defaultOrigins,...(process.env.ALLOWED_ORIGINS||'').split(',')].map(cleanOrigin).filter(Boolean))];
const corsOptions={origin:(origin,cb)=>{const clean=cleanOrigin(origin);if(!origin||origins.includes(clean))return cb(null,true);console.warn('Blocked CORS origin:',origin);return cb(null,false);},methods:['GET','POST','OPTIONS'],allowedHeaders:['Content-Type','Authorization','Cache-Control'],optionsSuccessStatus:204};
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors(corsOptions)); app.options(/.*/,cors(corsOptions)); app.use(express.json({limit:'10mb'})); app.use(rateLimit({windowMs:60000,limit:120}));
// Browser API routes are protected by strict CORS and WordPress itself authenticates publishing credentials.
// ADMIN_TOKEN is intentionally not exposed to the public GitHub Pages frontend.
const guard=(req,res,next)=>next();
const normalizeWpUrl=value=>{let v=String(value||'').trim();if(!v)return'';if(!/^https?:\/\//i.test(v))v='https://'+v;const u=new URL(v);return `${u.protocol}//${u.host}${u.pathname.replace(/\/(wp-admin|wp-login\.php|wp-json).*$/i,'').replace(/\/$/,'')}`};
const authHeader=w=>`Basic ${Buffer.from(`${w.username}:${w.appPassword}`).toString('base64')}`;
const parseBody=async r=>{const t=await r.text();try{return t?JSON.parse(t):{}}catch{return{raw:t}}};
const fetchTimed=(url,opts={},ms=15000)=>fetch(url,{...opts,signal:AbortSignal.timeout(ms),redirect:'follow'});
async function discoverWp(w){
  const site=normalizeWpUrl(w.url); if(!site)throw Object.assign(new Error('Enter your WordPress Site URL.'),{code:'missing_site'});
  const attempts=[]; let discovered='';
  try{const h=await fetchTimed(site,{method:'HEAD'});const link=h.headers.get('link')||'';const m=link.match(/<([^>]+)>;\s*rel=["']?https:\/\/api\.w\.org\/["']?/i);if(m)discovered=m[1]}catch(e){attempts.push({url:site,reason:e.message})}
  const candidates=[discovered,`${site}/wp-json/`,`${site}/?rest_route=/`].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);
  for(const root of candidates){try{const r=await fetchTimed(root,{headers:{Accept:'application/json'}});const j=await parseBody(r);if(r.ok && (Array.isArray(j.namespaces)?j.namespaces.includes('wp/v2'):j.routes && Object.keys(j.routes).some(k=>k.startsWith('/wp/v2')))){return{site,root:root.endsWith('/')?root:root+'/',index:j}}attempts.push({url:root,status:r.status,message:j.message||String(j.raw||'').slice(0,120)})}catch(e){attempts.push({url:root,reason:e.message})}}
  const err=Object.assign(new Error('WordPress REST API was not found. In WordPress, open Settings → Permalinks and click Save Changes, then check that security/cache plugins are not blocking REST API access.'),{code:'rest_not_found',attempts});throw err;
}
const routeUrl=(root,path)=>root.includes('?rest_route=')?`${root}${encodeURI(path.replace(/^\/?/,'wp/v2/'))}`:`${root}wp/v2/${path.replace(/^\//,'')}`;
async function wpFetch(w,path,opts={}){const d=w.restRoot?{root:w.restRoot,site:normalizeWpUrl(w.url)}:await discoverWp(w);const url=routeUrl(d.root,path);const r=await fetchTimed(url,{...opts,headers:{Accept:'application/json',Authorization:authHeader(w),...(opts.headers||{})}},30000);const j=await parseBody(r);if(!r.ok){const err=Object.assign(new Error(j.message||`WordPress returned ${r.status}`),{status:r.status,wpCode:j.code,details:j.data,url});throw err}return j}
function wpError(e){
 const status=e.status||400,code=e.wpCode||e.code||'wordpress_error';let message=e.message||'WordPress connection failed.';
 if(status===401||code==='rest_not_logged_in'||code==='incorrect_password'||code==='invalid_username')message='WordPress authentication failed. Re-enter the WordPress username (or email if your site accepts it) and a NEW Application Password, then test again.';
 else if(status===403)message='WordPress authenticated the request but blocked access. Check the user role/capabilities and any Hostinger/security plugin rules.';
 else if(status===404||code==='rest_no_route')message='WordPress REST route was not found. Aura tried REST discovery; re-save Settings → Permalinks and check security/cache plugins.';
 return{error:message,code,status,details:e.details||null,url:e.url||null};
}
const slug=s=>s.toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g,'').trim().replace(/[\s_]+/g,'-').replace(/-+/g,'-');
async function termId(w,type,name){let a=await wpFetch(w,`${type}?search=${encodeURIComponent(name)}&per_page=100`);let hit=a.find(x=>x.name.toLowerCase()===name.toLowerCase());if(hit)return hit.id;return (await wpFetch(w,type,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})})).id}
async function uploadMedia(w,file,alt=''){const r=await wpFetch(w,'media',{method:'POST',headers:{'Content-Type':file.mimetype||'application/octet-stream','Content-Disposition':`attachment; filename="${file.originalname.replace(/"/g,'')}"`},body:file.buffer});if(alt)await wpFetch(w,`media/${r.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alt_text:alt})});return r}
function render(post,media={}){let html=''; for(const s of post.sections||[]){if(s.type==='heading')html+=`<h${s.level||2}>${s.text||''}</h${s.level||2}>`;else if(s.type==='paragraph'||s.type==='intro')html+=`<p>${s.content||''}</p>`;else if(s.type==='html')html+=s.content||'';else if(s.type==='image'){const m=media[s.file];html+=m?`<figure class="wp-block-image"><img src="${m.source_url}" alt="${s.alt||''}"></figure>`:`<!-- AURA:MISSING:${s.file} -->`;}else if(s.type==='ad')html+=`<!-- AURA:AD:${s.slot||'article_ad'} --><div class="aura-ad-slot" data-slot="${s.slot||'article_ad'}"></div>`;else if(s.type==='checklist')html+=`<ul>${(s.items||[]).map(x=>`<li>${x}</li>`).join('')}</ul>`;} return html}
function validate(p){const e=[]; if(!p.post_id)e.push('post_id');if(!p.title)e.push('title');if(!(p.sections||[]).length)e.push('sections');if(!p.slug)p.slug=slug(p.title||'post'); const imgs=(p.sections||[]).filter(x=>x.type==='image');return {ok:!e.length,errors:e,requiredImages:imgs.map(x=>x.file),featured:p.featured_image?.file||null}}
app.get('/',(req,res)=>res.status(200).type('html').send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aura Publisher API</title><style>body{font-family:system-ui;background:#050814;color:#eaf3ff;display:grid;place-items:center;min-height:100vh;margin:0}.card{max-width:720px;padding:32px;border:1px solid #1f6fff;border-radius:22px;background:#091126;box-shadow:0 0 60px #075cff44}h1{color:#7fb7ff}.gold{color:#e7bd54}code{background:#020713;padding:3px 7px;border-radius:7px}</style></head><body><main class="card"><div class="gold">✝</div><h1>⚡ Aura Publisher API</h1><p>The Render backend is online.</p><p>Frontend: <code>https://zayaiken21.github.io/Aura-Publisher/</code></p><p>Health: <code>/healthz</code></p><p>Browser API access is restricted to the configured GitHub Pages origin. No browser access token is required.</p></main></body></html>`));
app.get('/healthz',(q,r)=>r.json({ok:true,status:'online',service:'Aura Publisher Pro API',version:'2.1.0'}));
app.get('/health',(q,r)=>r.json({ok:true,status:'online',service:'Aura Publisher Pro API',version:'2.1.0'}));
app.post('/api/wp/test',guard,async(req,res)=>{try{const w=req.body.wordpress||{};const d=await discoverWp(w);const creds={...w,url:d.site,restRoot:d.root};const me=await wpFetch(creds,'users/me?context=edit');res.json({ok:true,site:d.site,restRoot:d.root,user:{id:me.id,name:me.name,slug:me.slug,username:me.username||me.slug,email:me.email||''},capabilities:me.capabilities||{},message:'WordPress connected successfully.'})}catch(e){const out=wpError(e);res.status(out.status>=500?502:400).json(out)}});
app.post('/api/validate',guard,(req,res)=>res.json(validate(req.body.post||{})));
app.post('/api/import',guard,upload.array('files',100),async(req,res)=>{try{let posts=[],assets=[];for(const f of req.files||[]){const n=f.originalname.toLowerCase();if(n.endsWith('.json')){const j=JSON.parse(f.buffer.toString());posts.push(...(Array.isArray(j)?j:(j.posts||[j])))}else if(n.endsWith('.csv')){const lines=f.buffer.toString().split(/\r?\n/).filter(Boolean),h=lines.shift().split(',').map(x=>x.trim());for(const line of lines){const c=line.match(/("[^"]*(?:""[^"]*)*"|[^,]*)(?:,|$)/g)?.map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replace(/""/g,'"'))||[];const o=Object.fromEntries(h.map((k,i)=>[k,c[i]||'']));posts.push({post_id:o.post_id||crypto.randomUUID(),title:o.title,slug:o.slug||slug(o.title||''),category:o.category?[o.category]:[],tags:o.tags?o.tags.split('|').map(x=>x.trim()):[],excerpt:o.excerpt||'',status:o.status||'draft',sections:[{type:'intro',content:o.content||o.focus||''}]})}}else if(n.endsWith('.md')||n.endsWith('.txt')||n.endsWith('.html')){const text=f.buffer.toString();posts.push({post_id:f.originalname.replace(/\..+$/,''),title:text.split(/\r?\n/).find(Boolean)?.replace(/^#+\s*/,'')||f.originalname,sections:[{type:'html',content:n.endsWith('.html')?text:`<p>${text.replace(/\n\n/g,'</p><p>')}</p>`}],status:'draft'})}else if(n.endsWith('.docx')){const x=await mammoth.convertToHtml({buffer:f.buffer});posts.push({post_id:f.originalname.replace(/\.docx$/i,''),title:f.originalname.replace(/\.docx$/i,''),sections:[{type:'html',content:x.value}],status:'draft'})}else if(n.endsWith('.pdf')){const x=await pdf(f.buffer);posts.push({post_id:f.originalname.replace(/\.pdf$/i,''),title:x.text.split(/\r?\n/).find(Boolean)||f.originalname,sections:[{type:'paragraph',content:x.text}],status:'draft'})}else if(n.endsWith('.zip')){const z=new AdmZip(f.buffer);for(const e of z.getEntries()){if(e.entryName.toLowerCase().endsWith('.json')){const j=JSON.parse(e.getData().toString());posts.push(...(Array.isArray(j)?j:(j.posts||[j])))}else if(/\.(png|jpe?g|webp)$/i.test(e.entryName))assets.push(e.entryName)}}else if(/\.(png|jpe?g|webp)$/i.test(n))assets.push(f.originalname)}res.json({posts:posts.map(p=>({...p,validation:validate(p)})),assets})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/publish',guard,upload.array('assets',100),async(req,res)=>{try{const w=JSON.parse(req.body.wordpress),p=JSON.parse(req.body.post);const v=validate(p);if(!v.ok)return res.status(422).json(v);const files=Object.fromEntries((req.files||[]).map(f=>[f.originalname,f]));const media={};for(const name of [...v.requiredImages,v.featured].filter(Boolean)){if(files[name])media[name]=await uploadMedia(w,files[name],(p.sections||[]).find(x=>x.file===name)?.alt||p.featured_image?.alt||'')}
const cats=[];for(const x of p.category||p.categories||[])cats.push(await termId(w,'categories',x));const tags=[];for(const x of p.tags||[])tags.push(await termId(w,'tags',x));const body={title:p.title,slug:p.slug||slug(p.title),excerpt:p.excerpt||'',content:render(p,media),status:p.status||'draft',categories:cats,tags,featured_media:v.featured&&media[v.featured]?.id||0};if(p.date)body.date=p.date;const out=await wpFetch(w,'posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});res.json({ok:true,id:out.id,link:out.link,status:out.status})}catch(e){const out=wpError(e);res.status(400).json(out)}});
app.post('/api/generate',guard,async(req,res)=>{if(!process.env.OPENAI_API_KEY)return res.status(400).json({error:'API automation is disabled. Use ChatGPT Pro Mode import, or configure OPENAI_API_KEY.'});try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6',input:`Return only valid JSON matching Aura post schema. ${JSON.stringify(req.body)}`})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'OpenAI error');res.json(j)}catch(e){res.status(400).json({error:e.message})}});
app.use((req,res)=>res.status(404).json({error:'Route not found',path:req.path}));
app.use((e,q,r,n)=>r.status(400).json({error:e.message}));
app.listen(PORT,'0.0.0.0',()=>console.log(`Aura API listening on 0.0.0.0:${PORT}`));
